### ISSUE TITLE
Root Directory

### ISSUE THREAD

**Issue by sirfunkbutter** [Blackop778/MineCalc#1]
MineCalc when opened in eclipse and used as a root directory does not work and says no project found.

**Comment by Blackop778** [comment]
Did you try running gradlew eclipse in the command line?

**Comment by Blackop778** [comment]
Oops. Try running 'gradlew eclipse' at the MineCalc folder then opening it in eclipse.

**Comment by sirfunkbutter** [comment]
Still not working. Also the setup_eclipse still errors out hre on my PC but it does go a lot further and downloads a bunch

**Comment by Blackop778** [comment]
What is the error message?

**Comment by Blackop778** [comment]
Are there any computers that you have access to where you can run `setup-eclipse`?
